language: swift
os: osx
osx_image: xcode10.2
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - PROJECT=SwiftErrorHandler.xcodeproj
    - SCHEME=SwiftErrorHandler-Package
    - EXPANDED_CODE_SIGN_IDENTITY=""
    - EXPANDED_CODE_SIGN_IDENTITY_NAME=""
    - EXPANDED_PROVISIONING_PROFILE=""
    - DESTINATION="platform=iOS Simulator,name=iPhone XS"
    - CC_TEST_REPORTER_ID=f9052cf7f98bd46742d8f3f5d140a053f8cfb4031046eb238d1e5de9b460ac6b
install:
  - git config --add diff.renamelimit 0

jobs:
  include:
    - stage: lint
      script:
        - swiftlint
        - pod lib lint
    - stage: test
      before_script:
        - gem install slather
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - set -o pipefail
        - xcodebuild -version
        - xcodebuild -showsdks
        - swift package generate-xcodeproj --xcconfig-overrides ./Sources/ios.xcconfig
        - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -enableCodeCoverage YES clean build test | xcpretty
      after_script:
        - slather
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - stage: deploy
      if: tag IS present
      before_deploy:
        - brew update
        - brew outdated carthage || brew upgrade carthage
        - pod trunk push --allow-warnings
        - swift package generate-xcodeproj --xcconfig-overrides ./Sources/ios.xcconfig
        - carthage version
        - carthage build --no-skip-current
        - carthage archive SwiftErrorHandler
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: SwiftErrorHandler.framework.zip
        skip_cleanup: true
        on:
          repo: stefanrenne/SwiftErrorHandler
          tags: true
